openapi: "3.0.3"
info:
  title: "Application API"
  description: "Application API"
  version: "1.0.0"
servers:
  - url: "http://localhost:8080"
paths:
  /api/auth/register:
    post:
      description: "To register a new user"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "A"
components:
  schemas: { }